"""Tests for the RLE BYOH invocation contract this harness has to speak.

The lifecycle assertions below are RLE's, not ours, and are transcribed from
`ByohRolloutTargetInvoker`: the acknowledgement must be exactly `202` (not merely 2xx), the poll
resource is `{baseUrl}/rollouts/{operation_id}` derived by RLE from the *registered* base URL, and
the operation id is generated by RLE -- a harness that mints its own is never polled at the address
RLE is watching.
"""

from __future__ import annotations

import json
import os

import pytest
from fastapi.testclient import TestClient

from app import (
    ROLLOUTS,
    InvocationRequest,
    RolloutContext,
    _task_selector_from_agent_input,
    app,
)

ROLLOUT_CONTEXT = {
    "model_endpoint": "https://proxy.invalid/v1",
    "model_api_key": "session-key",
    "mcp_endpoint": "https://tools.invalid/tools",
    "mcp_bearer_token": "tools-token",
    "mcp_session_id": "session-abc",
}


def _rendered_agent_input(
    task_index: int = 0, split: str = "FineEnvs/data-agent-harbor-train"
) -> list[dict[str, object]]:
    """Builds the `agent_input` RLE renders from a `reset` observation, for request fixtures.

    `TaskObservation` sets an explicit `prompt` field, so RLE takes that string verbatim as the
    one user message's `content` -- see `RolloutObservationRenderer` upstream and
    `app._task_selector_from_agent_input`. `prompt` carries only what that selector reads.
    """
    return [{"role": "user", "content": json.dumps({"task_index": task_index, "split": split})}]


AGENT_INPUT = _rendered_agent_input()


def test_rollout_context_accepts_rles_current_wire_contract():
    parsed = RolloutContext.model_validate(ROLLOUT_CONTEXT)
    assert parsed.model_endpoint == "https://proxy.invalid/v1"
    assert parsed.model_api_key == "session-key"
    assert parsed.mcp_endpoint == "https://tools.invalid/tools"
    assert parsed.mcp_bearer_token == "tools-token"


def test_rollout_context_still_requires_every_field():
    """A silently-defaulted field would send the agent at the wrong model or drop its tool token."""
    for omit in ROLLOUT_CONTEXT:
        with pytest.raises(Exception):
            RolloutContext.model_validate({k: v for k, v in ROLLOUT_CONTEXT.items() if k != omit})


def test_invocation_uses_rles_operation_id_rather_than_minting_one():
    request = InvocationRequest.model_validate({
        "rollout_id": "rollout-1",
        "operation_id": "operation-1",
        "agent_input": _rendered_agent_input(task_index=3),
        "rollout_context": ROLLOUT_CONTEXT,
    })
    assert request.operation_id == "operation-1"
    assert request.rollout_id == "rollout-1"


def test_dispatch_acknowledges_with_202_and_a_poll_interval(monkeypatch):
    """RLE checks for `202` exactly, and holds `retry_after_ms` to [250, 15000]."""
    async def never_finishes(rollout_id, operation_id, rollout_context, agent_input):
        import asyncio

        await asyncio.sleep(3600)

    monkeypatch.setattr("app.run_harness_rollout", never_finishes)
    with TestClient(app) as client:
        response = client.post("/invoke", json={
            "rollout_id": "rollout-2",
            "operation_id": "operation-2",
            "agent_input": AGENT_INPUT,
            "rollout_context": ROLLOUT_CONTEXT,
        })
        assert response.status_code == 202
        assert 250 <= response.json()["retry_after_ms"] <= 15000

        # RLE derives this path itself from the registered base URL; the harness does not get to
        # choose it, so serving anything else means never being polled.
        poll = client.get("/invoke/rollouts/operation-2")
        assert poll.status_code == 200
        assert poll.json()["status"] == "running"

        assert client.delete("/invoke/rollouts/operation-2").status_code == 204
        assert client.get("/invoke/rollouts/operation-2").status_code == 404


def test_poll_reports_the_answer_under_output_text(monkeypatch):
    async def succeeds(rollout_id, operation_id, rollout_context, agent_input):
        return "Web Development"

    monkeypatch.setattr("app.run_harness_rollout", succeeds)
    with TestClient(app) as client:
        client.post("/invoke", json={
            "rollout_id": "rollout-3",
            "operation_id": "operation-3",
            "agent_input": AGENT_INPUT,
            "rollout_context": ROLLOUT_CONTEXT,
        })
        for _ in range(200):
            body = client.get("/invoke/rollouts/operation-3").json()
            if body["status"] != "running":
                break
        assert body["status"] == "succeeded"
        assert body["output_text"] == "Web Development"


def test_a_failed_rollout_is_reported_on_the_poll_not_the_dispatch(monkeypatch):
    """The dispatch is already answered by the time work starts, so a failure has nowhere else to go."""
    async def explodes(rollout_id, operation_id, rollout_context, agent_input):
        raise RuntimeError("sandbox refused to start")

    monkeypatch.setattr("app.run_harness_rollout", explodes)
    with TestClient(app) as client:
        assert client.post("/invoke", json={
            "rollout_id": "rollout-4",
            "operation_id": "operation-4",
            "agent_input": AGENT_INPUT,
            "rollout_context": ROLLOUT_CONTEXT,
        }).status_code == 202
        for _ in range(200):
            body = client.get("/invoke/rollouts/operation-4").json()
            if body["status"] != "running":
                break
        assert body["status"] == "failed"
        assert "sandbox refused to start" in body["error"]["message"]


def test_task_selector_recovers_what_reset_pinned_from_the_rendered_agent_input():
    """RLE no longer sends `task_index`/`split` directly -- it renders `reset`'s observation into
    a chat message and this is the harness's one chance to recover them from it."""
    rendered = _rendered_agent_input(task_index=7, split="FineEnvs/data-agent-harbor-validation")
    assert _task_selector_from_agent_input(rendered) == {
        "task_index": 7,
        "split": "FineEnvs/data-agent-harbor-validation",
    }


@pytest.mark.parametrize(
    "agent_input",
    [
        [],
        [{"role": "user", "content": "not json"}],
        [{"role": "user"}],
        [{"role": "user", "content": "[1, 2, 3]"}],
    ],
)
def test_task_selector_tolerates_an_empty_or_malformed_agent_input(agent_input):
    """RLE always renders at least one well-formed message in practice, but a harness this
    permissive should fall back to `run_harness_rollout`'s own defaults rather than crash."""
    assert _task_selector_from_agent_input(agent_input) == {}


def teardown_function() -> None:
    for operation_id in list(ROLLOUTS._states):  # noqa: SLF001 - test cleanup
        ROLLOUTS.withdraw(operation_id)
