"""Tests for the RLE BYOH invocation contract this harness has to speak.

These exist because the contract drifted once without anything failing until a live rollout: RLE
renamed three `rollout_context` fields, and since they are required on a pydantic model, the only
symptom was a `422` on dispatch -- which reads like a broken harness rather than version skew.

The lifecycle assertions below are RLE's, not ours, and are transcribed from
`ByohRolloutTargetInvoker`: the acknowledgement must be exactly `202` (not merely 2xx), the poll
resource is `{baseUrl}/rollouts/{operation_id}` derived by RLE from the *registered* base URL, and
the operation id is generated by RLE -- a harness that mints its own is never polled at the address
RLE is watching.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

os.environ.setdefault("HARNESS_SERVER_URL", "https://harbor.invalid")
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from fastapi.testclient import TestClient  # noqa: E402

from app import ROLLOUTS, InvocationRequest, RolloutContext, app  # noqa: E402

MASTER_CONTEXT = {
    "model_endpoint": "https://proxy.invalid/v1",
    "model_api_key": "session-key",
    "sandbox_tools_endpoint": "https://tools.invalid/tools",
    "sandbox_tools_token": "tools-token",
}
# The spelling RLE used before the rename. A deployed harness outlives a single RLE release, so
# both have to keep working -- see the note on `RolloutContext`.
LEGACY_CONTEXT = {
    "capture_proxy_endpoint": "https://proxy.invalid/v1",
    "capture_proxy_session_key": "session-key",
    "sandbox_tools_endpoint": "https://tools.invalid/tools",
    "sandbox_tools_bearer_token": "tools-token",
}


@pytest.mark.parametrize("context", [MASTER_CONTEXT, LEGACY_CONTEXT], ids=["master", "legacy"])
def test_both_wire_spellings_of_rollout_context_are_accepted(context):
    parsed = RolloutContext.model_validate(context)
    assert parsed.model_endpoint == "https://proxy.invalid/v1"
    assert parsed.model_api_key == "session-key"
    assert parsed.sandbox_tools_endpoint == "https://tools.invalid/tools"
    assert parsed.sandbox_tools_token == "tools-token"


def test_rollout_context_still_requires_every_field():
    """A silently-defaulted field would send the agent at the wrong model or drop its tool token."""
    for omit in MASTER_CONTEXT:
        with pytest.raises(Exception):
            RolloutContext.model_validate({k: v for k, v in MASTER_CONTEXT.items() if k != omit})


def test_invocation_uses_rles_operation_id_rather_than_minting_one():
    request = InvocationRequest.model_validate({
        "rollout_id": "rollout-1",
        "operation_id": "operation-1",
        "agent_input": {"task_index": 3},
        "rollout_context": MASTER_CONTEXT,
    })
    assert request.operation_id == "operation-1"
    assert request.rollout_id == "rollout-1"


def test_dispatch_acknowledges_with_202_and_a_poll_interval(monkeypatch):
    """RLE checks for `202` exactly, and holds `retry_after_ms` to [250, 15000]."""
    async def never_finishes(rollout_id, rollout_context, agent_input):
        import asyncio

        await asyncio.sleep(3600)

    monkeypatch.setattr("app.run_harness_rollout", never_finishes)
    with TestClient(app) as client:
        response = client.post("/invoke", json={
            "rollout_id": "rollout-2",
            "operation_id": "operation-2",
            "agent_input": {"task_index": 0},
            "rollout_context": MASTER_CONTEXT,
        })
        assert response.status_code == 202
        assert 250 <= response.json()["retry_after_ms"] <= 15000

        # RLE derives this path itself from the registered base URL; the harness does not get to
        # choose it, so serving anything else means never being polled.
        poll = client.get("/invoke/rollouts/operation-2")
        assert poll.status_code == 200
        assert poll.json()["status"] == "running"

        assert client.delete("/invoke/rollouts/operation-2").status_code == 204
        assert client.get("/invoke/rollouts/operation-2").status_code == 404


def test_poll_reports_the_answer_under_output_text(monkeypatch):
    async def succeeds(rollout_id, rollout_context, agent_input):
        return "Web Development"

    monkeypatch.setattr("app.run_harness_rollout", succeeds)
    with TestClient(app) as client:
        client.post("/invoke", json={
            "rollout_id": "rollout-3",
            "operation_id": "operation-3",
            "agent_input": {"task_index": 0},
            "rollout_context": MASTER_CONTEXT,
        })
        for _ in range(200):
            body = client.get("/invoke/rollouts/operation-3").json()
            if body["status"] != "running":
                break
        assert body["status"] == "succeeded"
        assert body["output_text"] == "Web Development"


def test_a_failed_rollout_is_reported_on_the_poll_not_the_dispatch(monkeypatch):
    """The dispatch is already answered by the time work starts, so a failure has nowhere else to go."""
    async def explodes(rollout_id, rollout_context, agent_input):
        raise RuntimeError("sandbox refused to start")

    monkeypatch.setattr("app.run_harness_rollout", explodes)
    with TestClient(app) as client:
        assert client.post("/invoke", json={
            "rollout_id": "rollout-4",
            "operation_id": "operation-4",
            "agent_input": {"task_index": 0},
            "rollout_context": MASTER_CONTEXT,
        }).status_code == 202
        for _ in range(200):
            body = client.get("/invoke/rollouts/operation-4").json()
            if body["status"] != "running":
                break
        assert body["status"] == "failed"
        assert "sandbox refused to start" in body["error"]["message"]


def teardown_function() -> None:
    for operation_id in list(ROLLOUTS._states):  # noqa: SLF001 - test cleanup
        ROLLOUTS.withdraw(operation_id)
